name: Ephemeral Test Using Testkube
on:
  pull_request: 

jobs:
  testkube-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml

      - name: Configure and Install Testkube
        run: |
          helm repo add kubeshop https://kubeshop.github.io/helm-charts
          helm repo update
          helm upgrade testkube kubeshop/testkube --install --create-namespace --namespace testkube --set testkube-api.cloud.key=${{ secrets.TESTKUBE_API_TOKEN }} --set testkube-api.cloud.orgId=${{ secrets.TESTKUBE_ORG_ID }} --set testkube-api.cloud.envId=${{ secrets.TESTKUBE_ENV_ID }} --set testkube-api.minio.enabled=false --set mongodb.enabled=false --set testkube-dashboard.enabled=false --set testkube-api.cloud.url=agent.testkube.io:443

      - name: Check Pods Status
        run: |
          kubectl get pods --all-namespaces -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          kubectl wait --for=condition=Ready pod/$POD_NAME -n testkube --timeout=150s

      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1        
      - run: |
          testkube create tw --name curl-sample -f test-workflow.yaml
          testkube run tw curl-sample -f --config url=http://nginx-service.default.svc.cluster.local
