name: Ephemeral Test Using Testkube
on:
  pull_request: 

jobs:
  testkube-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Kind Cluster
        uses: helm/kind-action@v1.9.0

      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml

      - name: Setup Testkube CLI
        run: |
          wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add -
          echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y testkube

      - name: Validate Testkube CLI Installation
        run: |
          testkube version

      - name: Configure Testkube Agent
        run: |
          testkube pro init --agent-token=${{ secrets.TESTKUBE_API_TOKEN }} --org-id=${{ secrets.TESTKUBE_ORG_ID }} --env-id=${{ secrets.TESTKUBE_ENV_ID }}

      - name: Check Pods Status
        run: |
          kubectl get pods --all-namespaces -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          kubectl wait --for=condition=Ready pod/$POD_NAME -n testkube --timeout=100s

      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1        
      - run: |
          testkube create tw --name curl-sample -f test-workflow.yaml
          testkube run tw curl-sample -f --config url=http://nginx-service.default.svc.cluster.local
